### ISSUE TITLE
Go get does not work

### ISSUE THREAD

**Issue by bhartvigsen** [neex/phuip-fpizdam#11]
go version go1.6.2 linux/amd64

Ubuntu 16.04.5 LTS

$ go get github.com/neex/phuip-fpizdam
# github.com/neex/phuip-fpizdam
go/src/github.com/neex/phuip-fpizdam/requester.go:30: undefined: http.ErrUseLastResponse

**Comment by neex** [comment]
Your go version is too old. Please use the latest version.

**Comment by bhartvigsen** [comment]
Might be a good idea to update the readme with the required version

**Comment by neex** [comment]
Hi again,

The go version has been added to the readme. Thanks for your advise!
