### ISSUE TITLE
HTTP requests delay option

### ISSUE THREAD

**Issue by hountybunter** [neex/phuip-fpizdam#14]
Adding an option to configure a delay for the HTTP requests so it can evade rate limits or certain WAFs.

**Comment by neex** [comment]
Hi @hountybunter, 

I've implemented it, use it like `--delay 0.3s` (the reference for the format is [here](https://golang.org/pkg/time/#ParseDuration)).

Note that attacks will take much longer.

If it works, please close the ticket.

**Comment by hountybunter** [comment]
That was fast. Thanks!
