### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by 0x92bf** [neex/phuip-fpizdam#19]
go run main.go
# command-line-arguments
.\main.go:22:19: undefined: AttackParams
.\main.go:31:13: undefined: Methods
.\main.go:36:22: undefined: NewRequester
.\main.go:51:15: undefined: SetSetting
.\main.go:70:15: undefined: KillWorkers
.\main.go:84:19: undefined: Detect
.\main.go:86:16: undefined: errPisosBruteForbidden
.\main.go:105:14: undefined: Attack

**Comment by imlonghao** [comment]
···
go build
./phuip-fpizdam
```
