### ISSUE TITLE
Request to add new flag --logfile

### ISSUE THREAD

**Issue by yangsec888** [neex/phuip-fpizdam#28]
The flag will redirect the messages from the default stdin/out to logfile. This would give you the flexibility to review all messages at a later time. (use case example: large scan at night). 

I have this implemented in my fork you can use as the quick reference. Just my 2 cents. Thank you.

https://github.com/yangsec888/phuip-fpizdam/blob/master/main.go

**Comment by neex** [comment]
Thanks, added.

**Comment by yangsec888** [comment]
Awesome!
