### ISSUE TITLE
https issue

### ISSUE THREAD

**Issue by l3m0n** [neex/phuip-fpizdam#3]
phuip-fpizdam/requester.go

```
		cl: &http.Client{
			Transport: &http.Transport{
				DisableCompression: true,      // No "Accept-Encoding"
				TLSNextProto:       nextProto, // No http2
				Proxy:              http.ProxyFromEnvironment,
				TLSClientConfig:    &tls.Config{InsecureSkipVerify: true},
			},
			Timeout:       30 * time.Second,
			CheckRedirect: disableRedirects, // No redirects
		},
```

maybe you can add `TLSClientConfig:    &tls.Config{InsecureSkipVerify: true},`
Otherwise, it will appear `Q: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs`

**Comment by neex** [comment]
Ok, I've added it.

However, I believe that if you want to scan an IP it will be better if you try to extract the actual hostname from the certificate returned. Otherwise you won't get server_name settings matched, at least.

If you're satisfied, close the issue.
