### ISSUE TITLE
THIS IS DON'T WORK!!!

### ISSUE THREAD

**Issue by adobromilskiy** [neex/phuip-fpizdam#31]
Ho to run you sh*t?
I can't check any PHP file. Always base status code is 404.

Waste my time.

**Comment by neex** [comment]
Unfortunately, not all configurations are vulnerable. Probably most installations have been updated by now.

Base status code is the status code returned for url like `/path-to.php/%0Atest.php` (which should be the same as `/path-to.php` in the vulnerable configuration).
