### ISSUE TITLE
go install does not work

### ISSUE THREAD

**Issue by invidian** [neex/phuip-fpizdam#9]
When executing `go install github.com/neex/phuip-fpizdam`, following error is printed:
```sh
$ go install github.com/neex/phuip-fpizdam
can't load package: package github.com/neex/phuip-fpizdam: cannot find package "github.com/neex/phuip-fpizdam" in any of:
	/usr/lib/go/src/github.com/neex/phuip-fpizdam (from $GOROOT)
	/home/invidian/go/src/github.com/neex/phuip-fpizdam (from $GOPATH)
$ go version
go version go1.13.3 linux/amd64
```

**Comment by trungking** [comment]
Use go get instead

**Comment by invidian** [comment]
`go get` indeed works :+1: thanks!

Should README.md be updated regarding that?

**Comment by neex** [comment]
My bad. README updated.

**Comment by jdgregson** [comment]
Quick note for anyone else who hasn't used go before: try `~/go/bin/phuip-fpizdam` if your shell can't find `phuip-fpizdam` on its own.
